.SUFFIXES : .c .o
CC = gcc

INC =
LIBS = 
CFLAGS = 

OBJS_1 = client.o
TARGET_1 = client

all : 
	$(CC) -g -o client *.c #-lcrypto  $(LIBS)

clean :
	rm -rf $(TARGET_1) $(TARGET_1).exe core
new : 
	$(MAKE) clean 
	$(MAKE) 

